openapi: 3.0.0
info:
  title: Todo Service
paths:
  /user_todos/{user_id}:
    get:
      summary: Returns all the todos for a user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      properties:
        user_id:
          type: string
        todos:
          type: array
          items:
            $ref: "#/components/schemas/Todo"
      required: ["user_id", "todos"]
    Todo:
      type: object
      properties:
        title:
          type: string
      required: ["title"]
