openapi: 3.0.0
info:
  title: User Service
paths:
  /user/{id}:
    get:
      summary: Returns a user.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required: ["id", "name"]
